#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "Script directory: $SCRIPT_DIR"
VENV_DIR="$SCRIPT_DIR/venv"
echo "Virtual environment directory: $VENV_DIR"

if [ -d "$VENV_DIR" ]; then
    echo "Activating virtual environment in $VENV_DIR"
    source "$VENV_DIR/bin/activate"
else
    echo "Virtual environment not found in $VENV_DIR"
    exit 1
fi

# Execute your Python script
"$VENV_DIR/bin/python" "$SCRIPT_DIR/src/speedup.py"

exit 0
